import type { RawTournament } from './types'

export const seedTournaments: RawTournament[] = [
  {
    externalId: 'fide-candidates-2026',
    title: 'FIDE Candidates Tournament',
    sourceName: 'FIDE',
    sourceUrl: 'https://www.fide.com/',
    officialUrl: 'https://www.fide.com/',
    startsAt: '2026-06-01T09:30:00.000Z',
    endsAt: '2026-06-18T18:30:00.000Z',
    country: 'Canada',
    venue: 'Toronto Chess Hall',
    address: 'Toronto, Ontario, Canada',
    city: 'Toronto',
    locationMode: 'otb',
    fideRated: true,
    timeControl: 'classical',
    format: 'double round robin',
    tournamentType: 'International',
    organizerName: 'FIDE',
    organizerVerified: true,
    prizePool: { label: 'Official prize fund', verified: true },
    topPlayers: [
      { name: 'Gukesh Dommaraju', title: 'GM', rating: 2763, country: 'India' },
      { name: 'Hikaru Nakamura', title: 'GM', rating: 2789, country: 'United States' },
      { name: 'Fabiano Caruana', title: 'GM', rating: 2803, country: 'United States' },
    ],
    tags: ['fide', 'candidates', 'elite', 'classical'],
  },
  {
    externalId: 'tata-steel-chess-2027',
    title: 'Tata Steel Chess Masters',
    sourceName: 'Manual',
    sourceUrl: 'https://www.tatasteelchess.com/',
    officialUrl: 'https://www.tatasteelchess.com/',
    startsAt: '2027-01-15T10:00:00.000Z',
    endsAt: '2027-01-31T18:00:00.000Z',
    country: 'Netherlands',
    venue: 'Wijk aan Zee',
    address: 'Wijk aan Zee, Netherlands',
    city: 'Wijk aan Zee',
    locationMode: 'otb',
    fideRated: true,
    timeControl: 'classical',
    format: 'round robin',
    tournamentType: 'International',
    organizerName: 'Tata Steel Chess',
    organizerVerified: true,
    prizePool: { label: 'Invitational prize fund', verified: true },
    topPlayers: [
      { name: 'Anish Giri', title: 'GM', rating: 2749, country: 'Netherlands' },
      { name: 'Nodirbek Abdusattorov', title: 'GM', rating: 2765, country: 'Uzbekistan' },
    ],
    tags: ['tata steel', 'elite', 'classical'],
  },
  {
    externalId: 'lichess-titled-arena-may-2026',
    title: 'Official Lichess Titled Arena',
    sourceName: 'Lichess',
    sourceUrl: 'https://lichess.org/tournament',
    officialUrl: 'https://lichess.org/tournament',
    registrationUrl: 'https://lichess.org/tournament',
    startsAt: '2026-05-19T15:00:00.000Z',
    endsAt: '2026-05-19T18:00:00.000Z',
    country: 'Online',
    locationMode: 'online',
    fideRated: false,
    timeControl: 'blitz',
    format: 'arena',
    tournamentType: 'International',
    organizerName: 'Lichess',
    organizerVerified: true,
    prizePool: { label: 'Platform announced rewards', verified: true },
    topPlayers: [
      { name: 'Titled players only', title: 'GM/IM/FM/WGM' },
    ],
    tags: ['lichess', 'titled', 'arena', 'official'],
  },
  {
    externalId: 'aicf-national-rapid-open-2026',
    title: 'National Rapid Open Championship',
    sourceName: 'ChessResults',
    sourceUrl: 'https://chess-results.com/',
    officialUrl: 'https://chess-results.com/',
    registrationUrl: 'https://chess-results.com/',
    startsAt: '2026-08-10T04:30:00.000Z',
    endsAt: '2026-08-12T13:30:00.000Z',
    country: 'India',
    venue: 'Indoor Sports Complex',
    address: 'Gachibowli Indoor Stadium, Hyderabad, Telangana, India',
    city: 'Hyderabad',
    locationMode: 'otb',
    fideRated: true,
    timeControl: 'rapid',
    format: 'swiss',
    tournamentType: 'National',
    organizerName: 'State Chess Association',
    organizerVerified: true,
    prizePool: { label: 'INR 5,00,000', verified: true },
    topPlayers: [
      { name: 'Seeded titled players', title: 'GM/IM' },
    ],
    tags: ['chess-results', 'fide rated', 'national', 'rapid'],
  },
  {
    externalId: 'all-india-fide-rated-rapid-chessfusion-2026',
    title: 'All India FIDE Rated Rapid Chess Tournament - 2nd Edition',
    sourceName: 'ChessResults',
    sourceUrl: 'https://chess-results.com/',
    officialUrl: 'https://chess-results.com/',
    registrationUrl: 'https://chess-results.com/',
    startsAt: '2026-07-11T04:30:00.000Z',
    endsAt: '2026-07-11T13:30:00.000Z',
    country: 'India',
    venue: 'ChessFusion Tournament Venue',
    address: 'Bengaluru, Karnataka, India',
    city: 'Bengaluru',
    locationMode: 'otb',
    fideRated: true,
    timeControl: 'rapid',
    format: 's',
    tournamentType: 'National',
    organizerName: 'ChessFusion',
    organizerVerified: true,
    prizePool: { label: 'Published by organizer', verified: false },
    topPlayers: [
      { name: 'Starting list pending publication' },
    ],
    tags: ['chess-results', 'fide rated', 'all india', 'rapid', 'swiss'],
  },
  {
    externalId: 'check-n-mate-all-india-open-fide-rated-rapid-2026',
    title: '6th Check n Mate All India Open FIDE Rated Rapid Chess Tournament',
    sourceName: 'ChessResults',
    sourceUrl: 'https://chess-results.com/',
    officialUrl: 'https://chess-results.com/',
    registrationUrl: 'https://chess-results.com/',
    startsAt: '2026-08-15T04:30:00.000Z',
    endsAt: '2026-08-15T13:30:00.000Z',
    country: 'India',
    venue: 'Check n Mate Tournament Venue',
    address: 'Bengaluru, Karnataka, India',
    city: 'Bengaluru',
    locationMode: 'otb',
    fideRated: true,
    timeControl: 'rapid',
    format: 's',
    tournamentType: 'National',
    organizerName: 'Check n Mate',
    organizerVerified: true,
    prizePool: { label: 'Published by organizer', verified: false },
    topPlayers: [
      { name: 'Starting list pending publication' },
    ],
    tags: ['chess-results', 'fide rated', 'all india', 'open', 'rapid', 'swiss'],
  },
  {
    externalId: 'verified-academy-weekend-rapid',
    title: 'Verified Chess Academy Weekend Rapid',
    sourceName: 'Academy',
    sourceUrl: 'https://nivenxa.com/chess',
    registrationUrl: 'https://nivenxa.com/account/register',
    startsAt: '2026-05-23T04:30:00.000Z',
    endsAt: '2026-05-23T11:30:00.000Z',
    country: 'India',
    venue: 'Nivenxa Chess Studio',
    address: 'Madhapur, Hyderabad, Telangana, India',
    city: 'Hyderabad',
    locationMode: 'otb',
    fideRated: false,
    timeControl: 'rapid',
    format: 'swiss',
    tournamentType: 'Academy',
    organizerName: 'Nivenxa Chess Academy',
    organizerVerified: true,
    prizePool: { label: 'Trophies and academy rewards', verified: true },
    topPlayers: [
      { name: 'Academy invited players' },
    ],
    tags: ['academy', 'verified', 'rapid', 'local'],
  },
  {
    externalId: 'local-club-blitz-evening',
    title: 'City Club Blitz Evening',
    sourceName: 'Manual',
    sourceUrl: 'https://nivenxa.com/chess',
    startsAt: '2026-05-21T13:30:00.000Z',
    endsAt: '2026-05-21T15:30:00.000Z',
    country: 'India',
    venue: 'Community Chess Club',
    address: 'Secunderabad, Telangana, India',
    city: 'Secunderabad',
    locationMode: 'otb',
    fideRated: false,
    timeControl: 'blitz',
    format: 'swiss',
    tournamentType: 'Club',
    organizerName: 'Community Chess Club',
    organizerVerified: false,
    tags: ['club', 'local', 'blitz'],
  },
]
