import type { Product } from '@/types'
export type { Product }

export const products: Product[] = [
  // ─── Women's Relaxed Lounge Sets ─────────────────────────────────────────────
  {
    id: 'wls-01',
    name: 'Ivory Woven Lounge Set',
    price: 2999,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Relaxed co-ord set in cloud-soft modal-cotton blend. Woven texture, wide-leg trouser, boxy crop top.',
    fabric: '200 GSM Modal-Cotton Blend',
    colorway: 'Warm Ivory',
    gradient: 'linear-gradient(160deg, #EDE9DF 0%, #DDD8CB 100%)',
  },
  {
    id: 'wls-02',
    name: 'Sage Relaxed Co-Ord',
    price: 3299,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Muted sage French terry lounge set. Elastic-waist jogger, oversized pullover, everyday ease.',
    fabric: '220 GSM French Terry',
    colorway: 'Sage Mist',
    gradient: 'linear-gradient(160deg, #B5B9AE 0%, #9EA39A 100%)',
  },
  {
    id: 'wls-03',
    name: 'Blush Knit Lounge Set',
    price: 2999,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Dusty blush jersey knit set for slow mornings. Relaxed fit, minimal seaming, studio-to-street.',
    fabric: '200 GSM Jersey Knit',
    colorway: 'Dusty Blush',
    gradient: 'linear-gradient(160deg, #DEC0B8 0%, #C9A9A0 100%)',
  },

  // ─── Women's Indo-Western Comfortwear ────────────────────────────────────────
  {
    id: 'wiw-01',
    name: 'Kurta Palazzo Set',
    price: 4499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Terracotta rayon slub kurta with wide-leg palazzo. Delicate pintuck detail, relaxed Indo silhouette.',
    fabric: '280 GSM Rayon Slub',
    colorway: 'Terracotta Rose',
    gradient: 'linear-gradient(160deg, #C87B6A 0%, #A9604F 100%)',
  },
  {
    id: 'wiw-02',
    name: 'Kurta Dhoti Co-Ord',
    price: 4999,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Handloom cotton kurta and dhoti set. Relaxed modern fusion for elevated everyday wear.',
    fabric: '260 GSM Handloom Cotton',
    colorway: 'Natural Ecru',
    gradient: 'linear-gradient(160deg, #D4CCBC 0%, #BFB7A5 100%)',
  },
  {
    id: 'wiw-03',
    name: 'Block Print Palazzo Set',
    price: 5499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Chanderi cotton palazzo set with subtle block print. Indigo-stone tones, editorial Indo-Western form.',
    fabric: '300 GSM Chanderi Cotton',
    colorway: 'Indigo Stone',
    gradient: 'linear-gradient(160deg, #5A6678 0%, #3F4E5E 100%)',
  },

  // ─── Boys Premium Collections ─────────────────────────────────────────────────
  {
    id: 'bp-01',
    name: 'Heritage Track Set',
    price: 2799,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Charcoal French terry track set for active boys. Structured fit, reinforced stitching, built to last.',
    fabric: '260 GSM French Terry',
    colorway: 'Charcoal Marl',
    gradient: 'linear-gradient(160deg, #5C5A57 0%, #474542 100%)',
  },
  {
    id: 'bp-02',
    name: 'Canvas Co-Ord Set',
    price: 3199,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Bio-washed canvas shorts and overshirt set. Khaki tones, casual structure, weekend ready.',
    fabric: '280 GSM Bio-Washed Canvas',
    colorway: 'Kora Khaki',
    gradient: 'linear-gradient(160deg, #B5AA8E 0%, #A09480 100%)',
  },
  {
    id: 'bp-03',
    name: 'Utility Shorts Set',
    price: 2499,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Stonewashed olive utility shorts and tee set. Functional pockets, relaxed cut, durable everyday wear.',
    fabric: '240 GSM Stonewashed Cotton',
    colorway: 'Muted Olive',
    gradient: 'linear-gradient(160deg, #7A7F6A 0%, #5E6250 100%)',
  },

  // ─── Girls Premium Collections ────────────────────────────────────────────────
  {
    id: 'gp-01',
    name: 'Gathered Kurta Set',
    price: 2999,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Dusty rose cotton voile kurta with gathered hem and matching churidar. Soft, feminine, celebration-ready.',
    fabric: '240 GSM Cotton Voile',
    colorway: 'Dusty Rose',
    gradient: 'linear-gradient(160deg, #D4A8A0 0%, #BF9088 100%)',
  },
  {
    id: 'gp-02',
    name: 'Linen Co-Ord Set',
    price: 3299,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Pure linen top and wide-leg trouser in warm sand. Breathable, minimal, naturally styled.',
    fabric: '220 GSM Pure Linen',
    colorway: 'Warm Sand',
    gradient: 'linear-gradient(160deg, #D4C9B0 0%, #BFBA9E 100%)',
  },
  {
    id: 'gp-03',
    name: 'Printed Lounge Set',
    price: 2799,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Modal-blend lounge set in sage mauve with subtle print. Soft to touch, easy to wear, all day.',
    fabric: '200 GSM Modal Blend',
    colorway: 'Sage Mauve',
    gradient: 'linear-gradient(160deg, #C4B5C0 0%, #B0A0B0 100%)',
  },

  // ─── Kids Unisex Nightwear ────────────────────────────────────────────────────
  {
    id: 'kn-01',
    name: 'Cloud Soft Night Set',
    price: 1799,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Supima cotton night suit in gentle oat white. Silky-smooth finish, temperature-regulating, all-season comfort.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Oat White',
    gradient: 'linear-gradient(160deg, #EAE6DC 0%, #D8D4CA 100%)',
  },
  {
    id: 'kn-02',
    name: 'Forest Knit PJ Set',
    price: 1999,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Jersey knit pyjama set in muted sage green. Cosy rib cuffs, relaxed fit, gentle on skin.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Sage Green',
    gradient: 'linear-gradient(160deg, #8EA890 0%, #728C74 100%)',
  },
  {
    id: 'kn-03',
    name: 'Warm Stone Night Set',
    price: 1799,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Brushed cotton night set in warm stone beige. Ultra-soft brushed interior, full-season warmth.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Stone Beige',
    gradient: 'linear-gradient(160deg, #D0C4B0 0%, #C0B4A0 100%)',
  },

  // ─── Unisex Cargo Pants ───────────────────────────────────────────────────────
  {
    id: 'cargo-01',
    name: 'Charcoal Utility Cargo',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'Six-pocket utilitarian cargo cut in 320 GSM bio-washed cotton twill. Structured drape, relaxed fit.',
    fabric: '320 GSM Bio-Washed Cotton Twill',
    colorway: 'Washed Charcoal',
    gradient: 'linear-gradient(160deg, #4A4844 0%, #36332E 100%)',
  },
  {
    id: 'cargo-02',
    name: 'Kora Sand Cargo',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A sand-toned cargo in unbleached ecru cotton. Structured yet relaxed, for the minimalist wardrobe.',
    fabric: '300 GSM Enzyme-Washed Cotton',
    colorway: 'Kora Sand',
    gradient: 'linear-gradient(160deg, #D4CFBA 0%, #BFBA9E 100%)',
  },
  {
    id: 'cargo-03',
    name: 'Olive Expedition Cargo',
    price: 3799,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A muted olive cargo for the urban wanderer. Heavyweight stonewashed canvas, breathable in Indian heat.',
    fabric: '340 GSM Stonewashed Canvas',
    colorway: 'Muted Olive',
    gradient: 'linear-gradient(160deg, #7A7F6A 0%, #5E6250 100%)',
  },

  // ─── Unisex Oversize Tee Shirts ───────────────────────────────────────────────
  {
    id: 'tee-01',
    name: 'Oversized Heritage Tee',
    price: 1999,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Boxy drop-shoulder silhouette in dense 240 GSM combed cotton jersey. The foundational piece.',
    fabric: '240 GSM Combed Cotton Jersey',
    colorway: 'Ecru White',
    gradient: 'linear-gradient(160deg, #EAE5D8 0%, #D4CFBF 100%)',
  },
  {
    id: 'tee-02',
    name: 'Terracotta Washed Tee',
    price: 1999,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Sun-baked terracotta pigment dye over a structured oversized form. Earthy, lived-in warmth.',
    fabric: '240 GSM Pigment-Dyed Cotton',
    colorway: 'Sun-baked Terracotta',
    gradient: 'linear-gradient(160deg, #C47055 0%, #A05040 100%)',
  },
  {
    id: 'tee-03',
    name: 'Ink Drop Graphic Tee',
    price: 2199,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Minimal hand-drawn graphic on heavyweight charcoal jersey. Ring-spun for softness that ages beautifully.',
    fabric: '260 GSM Ring-Spun Cotton',
    colorway: 'Washed Charcoal',
    gradient: 'linear-gradient(160deg, #4A4844 0%, #36332E 100%)',
  },
]

export const getProductsByCategory = (category: Product['category']) =>
  products.filter((p) => p.category === category)

export const getProductsByGender = (gender: Product['gender']) =>
  products.filter((p) => p.gender === gender)
