import type { Product } from '@/types'
export type { Product }

export const products: Product[] = [

  // ─── Women's Relaxed Lounge Sets ─────────────────────────────────────────────
  {
    id: 'wls-01',
    name: 'Ivory Woven Lounge Set',
    price: 2999,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Relaxed co-ord set in cloud-soft modal-cotton blend. Woven texture, wide-leg trouser, boxy crop top.',
    fabric: '200 GSM Modal-Cotton Blend',
    colorway: 'Warm Ivory',
    gradient: 'linear-gradient(160deg, #EDE9DF 0%, #DDD8CB 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(237, 233, 223, 0.3)',
    fabricStory: {
      label: 'MODAL-COTTON BLEND',
      lines: ['Cloud-soft handle.', 'Drapes with ease.', 'Breathes through the day.'],
    },
    badges: ['Modal Blend', 'Relaxed Fit', 'Breathable'],
    dna: { fit: 'Relaxed Wide-Leg', fabric: 'Modal-Cotton Blend', finish: 'Natural', drape: 'Fluid', movement: 'Lounge & Studio' },
  },
  {
    id: 'wls-02',
    name: 'Sage Relaxed Co-Ord',
    price: 3299,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Muted sage French terry lounge set. Elastic-waist jogger, oversized pullover, everyday ease.',
    fabric: '220 GSM French Terry',
    colorway: 'Sage Mist',
    gradient: 'linear-gradient(160deg, #B5B9AE 0%, #9EA39A 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(158, 163, 154, 0.2)',
    fabricStory: {
      label: 'FRENCH TERRY',
      lines: ['Loop-back structure.', 'Warm without weight.', 'Garment-washed for softness.'],
    },
    badges: ['French Terry', 'Garment Washed', 'Oversized Fit'],
    dna: { fit: 'Oversized Relaxed', fabric: 'French Terry', finish: 'Garment Washed', drape: 'Soft Structure', movement: 'Everyday Ease' },
  },
  {
    id: 'wls-03',
    name: 'Blush Knit Lounge Set',
    price: 2999,
    category: 'women-lounge-sets',
    gender: 'women',
    description: 'Dusty blush jersey knit set for slow mornings. Relaxed fit, minimal seaming, studio-to-street.',
    fabric: '200 GSM Jersey Knit',
    colorway: 'Dusty Blush',
    gradient: 'linear-gradient(160deg, #DEC0B8 0%, #C9A9A0 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(222, 192, 184, 0.25)',
    fabricStory: {
      label: 'JERSEY KNIT',
      lines: ['Four-way stretch.', 'Minimal seam construction.', 'From studio to street.'],
    },
    badges: ['Jersey Knit', 'Four-Way Stretch', 'Minimal Seam'],
    dna: { fit: 'Relaxed', fabric: 'Jersey Knit', finish: 'Natural', drape: 'Fluid', movement: 'Studio & Street' },
  },

  // ─── Women's Indo-Western Comfortwear ────────────────────────────────────────
  {
    id: 'wiw-01',
    name: 'Kurta Palazzo / Terracotta',
    price: 4499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Terracotta rayon slub kurta with wide-leg palazzo. Delicate pintuck detail, relaxed Indo silhouette.',
    fabric: '280 GSM Rayon Slub',
    colorway: 'Terracotta Rose',
    gradient: 'linear-gradient(160deg, #C87B6A 0%, #A9604F 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(200, 123, 106, 0.2)',
    fabricStory: {
      label: 'RAYON SLUB',
      lines: ['Natural slub texture.', 'Lightweight drape.', 'Artisanal surface character.'],
    },
    badges: ['Rayon Slub', 'Pintuck Detail', 'Wide-Leg Silhouette'],
    dna: { fit: 'Indo Relaxed', fabric: 'Rayon Slub', finish: 'Natural', drape: 'Fluid', movement: 'Elevated Everyday' },
  },
  {
    id: 'wiw-02',
    name: 'Kurta Dhoti / Natural Ecru',
    price: 4999,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Handloom cotton kurta and dhoti set. Relaxed modern fusion for elevated everyday wear.',
    fabric: '260 GSM Handloom Cotton',
    colorway: 'Natural Ecru',
    gradient: 'linear-gradient(160deg, #D4CCBC 0%, #BFB7A5 100%)',
    status: 'LIMITED RUN',
    atmosphereColor: 'rgba(212, 204, 188, 0.25)',
    fabricStory: {
      label: 'HANDLOOM COTTON',
      lines: ['Woven by hand.', 'Irregular texture, intentional.', 'Heritage in every thread.'],
    },
    badges: ['Handloom Cotton', 'Heritage Weave', 'Limited Run'],
    dna: { fit: 'Indo Relaxed', fabric: 'Handloom Cotton', finish: 'Natural', drape: 'Structured', movement: 'Heritage Modern' },
  },
  {
    id: 'wiw-03',
    name: 'Block Print Palazzo / Indigo',
    price: 5499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Chanderi cotton palazzo set with subtle block print. Indigo-stone tones, editorial Indo-Western form.',
    fabric: '300 GSM Chanderi Cotton',
    colorway: 'Indigo Stone',
    gradient: 'linear-gradient(160deg, #5A6678 0%, #3F4E5E 100%)',
    status: 'LIMITED RUN',
    atmosphereColor: 'rgba(63, 78, 94, 0.2)',
    fabricStory: {
      label: 'CHANDERI COTTON',
      lines: ['Sheer-to-structured hand.', 'Block-printed by artisans.', 'Indigo mineral tones.'],
    },
    badges: ['Chanderi Cotton', 'Block Printed', 'Artisan Craft'],
    dna: { fit: 'Wide-Leg Palazzo', fabric: 'Chanderi Cotton', finish: 'Block Printed', drape: 'Fluid', movement: 'Editorial Heritage' },
  },

  // ─── Women's Indo-Western — image-backed colorways ───────────────────────────
  {
    id: 'wiw-04',
    name: 'Indo-Western / Mushroom Taupe',
    price: 4999,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Earthy mushroom-taupe handloom kurta set. Subtle textured weave, relaxed Indo silhouette, minimal embellishment.',
    fabric: '260 GSM Handloom Cotton',
    colorway: 'Mushroom Taupe',
    gradient: 'linear-gradient(160deg, #C4B8A8 0%, #AFA293 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(175, 162, 147, 0.22)',
    fabricStory: {
      label: 'HANDLOOM COTTON',
      body: 'Woven by hand in a warm mushroom-taupe tone. The irregular texture of handloom gives each piece subtle surface character — no two pieces are exactly alike.',
      lines: ['Woven by hand.', 'Irregular texture, intentional.', 'Heritage in every thread.'],
    },
    badges: ['Handloom Cotton', 'Heritage Weave', 'Relaxed Indo Fit'],
    dna: {
      fabric:    '260 GSM Handloom Cotton',
      structure: 'Relaxed Indo Silhouette',
      finish:    'Natural',
      movement:  'Elevated Everyday',
      climate:   'All-Season',
    },
    designedFor: ['Everyday elegance', 'Warm climate wear', 'Elevated casual'],
  },
  {
    id: 'wiw-05',
    name: 'Indo-Western / Oat Beige',
    price: 4499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Oat beige cotton kurta set. Soft neutral tone, clean Indo silhouette, easy everyday elegance.',
    fabric: '260 GSM Cotton Voile',
    colorway: 'Oat Beige',
    gradient: 'linear-gradient(160deg, #E2D9CC 0%, #CEC5B5 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(206, 197, 181, 0.22)',
    fabricStory: {
      label: 'COTTON VOILE',
      body: 'A light, breathable oat-toned voile that sits close to the skin without clinging. The neutral warmth makes it effortlessly wearable across seasons.',
      lines: ['Soft oat neutral.', 'Breathable voile structure.', 'Effortless Indo silhouette.'],
    },
    badges: ['Cotton Voile', 'Breathable', 'Everyday Indo'],
    dna: {
      fabric:    '260 GSM Cotton Voile',
      structure: 'Relaxed Indo Silhouette',
      finish:    'Natural',
      movement:  'Elevated Everyday',
      climate:   'Warm Climate',
    },
    designedFor: ['Daily wear', 'Warm weather', 'Understated elegance'],
    images: [
      { src: '/Premium Indo-Western Comfortwea/Indo-Western Comfortwea-oat beige-front.png', view: 'front' },
    ],
  },
  {
    id: 'wiw-06',
    name: 'Indo-Western / Oat Meal',
    price: 4499,
    category: 'women-indo-western',
    gender: 'women',
    description: 'Oatmeal-toned textured cotton kurta set. Raw, lived-in warmth — the understated Indo-Western essential.',
    fabric: '280 GSM Textured Cotton',
    colorway: 'Oat Meal',
    gradient: 'linear-gradient(160deg, #D8CFC0 0%, #C4BAA8 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(196, 186, 168, 0.22)',
    fabricStory: {
      label: 'TEXTURED COTTON',
      body: 'A slightly heavier textured cotton in a warm oatmeal tone. The surface has a quiet tactile quality — neither flat nor structured, sitting in between.',
      lines: ['Warm oatmeal tone.', 'Textured cotton surface.', 'Understated Indo essential.'],
    },
    badges: ['Textured Cotton', 'Relaxed Fit', 'Core Neutral'],
    dna: {
      fabric:    '280 GSM Textured Cotton',
      structure: 'Relaxed Indo Silhouette',
      finish:    'Natural',
      movement:  'Elevated Everyday',
      climate:   'All-Season',
    },
    designedFor: ['Daily wear', 'All-season layering', 'Quiet luxury'],
    images: [
      { src: '/Premium Indo-Western Comfortwea/Indo-Western Comfortwea-ota-meal-front.png', view: 'front' },
    ],
  },

  // ─── Boys Premium Collections ─────────────────────────────────────────────────
  {
    id: 'bp-01',
    name: 'Heritage Track Set',
    price: 2799,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Charcoal French terry track set for active boys. Structured fit, reinforced stitching, built to last.',
    fabric: '260 GSM French Terry',
    colorway: 'Charcoal Marl',
    gradient: 'linear-gradient(160deg, #5C5A57 0%, #474542 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(71, 69, 66, 0.18)',
    fabricStory: {
      label: 'FRENCH TERRY',
      lines: ['Reinforced construction.', 'Loop-back interior.', 'Active comfort, all day.'],
    },
    badges: ['French Terry', 'Reinforced Stitch', 'Active Fit'],
    dna: { fit: 'Structured Active', fabric: 'French Terry', finish: 'Natural', drape: 'Firm', movement: 'Active & Play' },
  },
  {
    id: 'bp-02',
    name: 'Canvas Co-Ord / Khaki',
    price: 3199,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Bio-washed canvas shorts and overshirt set. Khaki tones, casual structure, weekend ready.',
    fabric: '280 GSM Bio-Washed Canvas',
    colorway: 'Kora Khaki',
    gradient: 'linear-gradient(160deg, #B5AA8E 0%, #A09480 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(181, 170, 142, 0.22)',
    fabricStory: {
      label: 'BIO-WASHED CANVAS',
      lines: ['Enzyme-softened surface.', 'Structured without stiffness.', 'Weekend-ready weight.'],
    },
    badges: ['Bio-Washed Canvas', 'Relaxed Structure', 'Weekend Ready'],
    dna: { fit: 'Relaxed Casual', fabric: 'Bio-Washed Canvas', finish: 'Bio-Washed', drape: 'Soft Structure', movement: 'Weekend Ease' },
  },
  {
    id: 'bp-03',
    name: 'Utility Shorts Set / Olive',
    price: 2499,
    category: 'boys-premium',
    gender: 'kids',
    description: 'Stonewashed olive utility shorts and tee set. Functional pockets, relaxed cut, durable everyday wear.',
    fabric: '240 GSM Stonewashed Cotton',
    colorway: 'Muted Olive',
    gradient: 'linear-gradient(160deg, #7A7F6A 0%, #5E6250 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(94, 98, 80, 0.2)',
    fabricStory: {
      label: 'STONEWASHED COTTON',
      lines: ['Pre-washed softness.', 'Utility pocket construction.', 'Durable from day one.'],
    },
    badges: ['Stonewashed Cotton', 'Utility Pockets', 'Relaxed Cut'],
    dna: { fit: 'Relaxed Utility', fabric: 'Stonewashed Cotton', finish: 'Stonewashed', drape: 'Soft', movement: 'Active Everyday' },
  },

  // ─── Girls Premium Collections ────────────────────────────────────────────────
  {
    id: 'gp-01',
    name: 'Gathered Kurta / Dusty Rose',
    price: 2999,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Dusty rose cotton voile kurta with gathered hem and matching churidar. Soft, feminine, celebration-ready.',
    fabric: '240 GSM Cotton Voile',
    colorway: 'Dusty Rose',
    gradient: 'linear-gradient(160deg, #D4A8A0 0%, #BF9088 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(212, 168, 160, 0.22)',
    fabricStory: {
      label: 'COTTON VOILE',
      lines: ['Sheer, light construction.', 'Gathered hem detail.', 'Soft enough for celebration.'],
    },
    badges: ['Cotton Voile', 'Gathered Hem', 'Celebration Ready'],
    dna: { fit: 'Relaxed Kurta', fabric: 'Cotton Voile', finish: 'Natural', drape: 'Fluid', movement: 'Festive & Daily' },
  },
  {
    id: 'gp-02',
    name: 'Linen Co-Ord / Warm Sand',
    price: 3299,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Pure linen top and wide-leg trouser in warm sand. Breathable, minimal, naturally styled.',
    fabric: '220 GSM Pure Linen',
    colorway: 'Warm Sand',
    gradient: 'linear-gradient(160deg, #D4C9B0 0%, #BFBA9E 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(212, 201, 176, 0.25)',
    fabricStory: {
      label: 'PURE LINEN',
      lines: ['Natural linen weave.', 'Cool in Indian heat.', 'Softens beautifully with every wash.'],
    },
    badges: ['Pure Linen', 'Breathable Weave', 'Natural Finish'],
    dna: { fit: 'Wide-Leg Relaxed', fabric: 'Pure Linen', finish: 'Natural', drape: 'Structured-Fluid', movement: 'Everyday Comfort' },
  },
  {
    id: 'gp-03',
    name: 'Printed Lounge / Sage Mauve',
    price: 2799,
    category: 'girls-premium',
    gender: 'kids',
    description: 'Modal-blend lounge set in sage mauve with subtle print. Soft to touch, easy to wear, all day.',
    fabric: '200 GSM Modal Blend',
    colorway: 'Sage Mauve',
    gradient: 'linear-gradient(160deg, #C4B5C0 0%, #B0A0B0 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(176, 160, 176, 0.2)',
    fabricStory: {
      label: 'MODAL BLEND',
      lines: ['Silk-like softness.', 'Subtle surface print.', 'All-day breathable comfort.'],
    },
    badges: ['Modal Blend', 'Soft Print', 'All-Day Comfort'],
    dna: { fit: 'Relaxed Lounge', fabric: 'Modal Blend', finish: 'Natural', drape: 'Fluid', movement: 'Lounge & Play' },
  },

  // ─── Kids Unisex Nightwear ────────────────────────────────────────────────────
  {
    id: 'kn-01',
    name: 'Cloud Soft Night Set',
    price: 1799,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Supima cotton night suit in gentle oat white. Silky-smooth finish, temperature-regulating, all-season comfort.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Oat White',
    gradient: 'linear-gradient(160deg, #EAE6DC 0%, #D8D4CA 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(234, 230, 220, 0.25)',
    fabricStory: {
      label: 'ORGANIC COTTON-BAMBOO RIB',
      lines: ['Temperature-regulating.', 'Ultra-gentle on young skin.', 'Softer with every wash.'],
    },
    badges: ['Organic Cotton', 'Bamboo Blend', 'Temperature Regulating'],
    dna: { fit: 'Relaxed Sleep', fabric: 'Cotton-Bamboo Rib', finish: 'Natural', drape: 'Soft', movement: 'Sleep Comfort' },
  },
  {
    id: 'kn-02',
    name: 'Forest Knit PJ Set',
    price: 1999,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Jersey knit pyjama set in muted sage green. Cosy rib cuffs, relaxed fit, gentle on skin.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Sage Green',
    gradient: 'linear-gradient(160deg, #8EA890 0%, #728C74 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(114, 140, 116, 0.2)',
    fabricStory: {
      label: 'ORGANIC COTTON-BAMBOO RIB',
      lines: ['Rib-knit cuff detail.', 'Naturally moisture-wicking.', 'Forest-toned calm.'],
    },
    badges: ['Rib Cuffs', 'Moisture Wicking', 'Organic Blend'],
    dna: { fit: 'Relaxed Sleep', fabric: 'Cotton-Bamboo Rib', finish: 'Natural', drape: 'Soft', movement: 'Sleep Comfort' },
  },
  {
    id: 'kn-03',
    name: 'Warm Stone Night Set',
    price: 1799,
    category: 'kids-nightwear',
    gender: 'kids',
    description: 'Brushed cotton night set in warm stone beige. Ultra-soft brushed interior, full-season warmth.',
    fabric: '220 GSM Organic Cotton-Bamboo Rib',
    colorway: 'Stone Beige',
    gradient: 'linear-gradient(160deg, #D0C4B0 0%, #C0B4A0 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(208, 196, 176, 0.25)',
    fabricStory: {
      label: 'BRUSHED COTTON RIB',
      lines: ['Brushed interior surface.', 'Full-season warmth.', 'Stone mineral tones.'],
    },
    badges: ['Brushed Interior', 'Full-Season Warmth', 'Organic Cotton'],
    dna: { fit: 'Relaxed Sleep', fabric: 'Brushed Cotton Rib', finish: 'Brushed', drape: 'Soft', movement: 'Sleep Comfort' },
  },

  // ─── Unisex Cargo Pants — order: Sand Beige · Olive · Charcoal ───────────────
  {
    id: 'cargo-02',
    name: 'Utility Cargo / Sand Beige',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A sand-toned cargo in unbleached ecru cotton. Structured yet relaxed, for the minimalist wardrobe.',
    fabric: '300 GSM Enzyme-Washed Cotton',
    colorway: 'Sand Beige',
    gradient: 'linear-gradient(160deg, #D4CFBA 0%, #BFBA9E 100%)',
    defaultColor: 'sand-beige',
    featured: true,
    status: 'NIVENXA ESSENTIAL',
    atmosphereColor: 'rgba(212, 207, 186, 0.28)',
    fabricStory: {
      label: 'ENZYME-WASHED COTTON',
      body: 'Developed from unbleached ecru cotton and treated with an enzyme-softening process, this fabric delivers a naturally weathered hand-feel with structured drape. The 300 GSM weight ensures durability without stiffness.',
      spec: { gsm: '300 GSM', weave: 'Plain Weave', washMethod: 'Enzyme Wash', finish: 'Enzyme Softened', softness: 'Medium-Soft' },
      lines: ['Unbleached ecru structure.', 'Enzyme-softened finish.', 'Crafted for the understated wardrobe.'],
    },
    badges: ['Enzyme Softened', 'Relaxed Utility Fit', 'Structured Drape'],
    dna: {
      fabric:    '300 GSM Enzyme-Washed Cotton',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Enzyme Washed Softening',
      movement:  'Designed for Everyday Wear',
      climate:   'All-Season Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Reinforced seam at stress points',
      'Relaxed stacked hem profile',
      'Softened elasticated waistband',
      'Flat-felled interior seam finish',
    ],
    fitPhilosophy: 'Designed with a relaxed utility silhouette — a wider leg opening and structured drape creates natural stacking at the hem, allowing unrestricted movement across all terrains.',
    colorStory: { shade: 'Sand Beige', description: 'Unbleached ecru, softened through enzyme treatment to reveal a muted sand tone. Neither warm nor cool — a quiet neutral that anchors any wardrobe.' },
    stylingWith: ['Heavyweight oversized tee', 'Relaxed utility overshirt', 'Canvas slip-on footwear'],
    care: 'Machine wash cold, inside out. Tumble dry low. The enzyme-washed finish will deepen slightly with wear, improving in character over time.',
    designedFor: ['Everyday movement', 'Urban utility', 'Understated wardrobe systems'],
    whyItExists: 'Built to bridge structured utility with contemporary everyday wear — a garment that performs without announcing itself.',
    images: [
      { src: '/cargos/cargo-sand-beige-front.png',   view: 'front'   },
      { src: '/cargos/cargo-sand-beige-back.png',    view: 'back'    },
      { src: '/cargos/cargo-sand-beige-side.png',    view: 'side'    },
      { src: '/cargos/cargo-sand-beige-details.png', view: 'details' },
    ],
  },
  {
    id: 'cargo-03',
    name: 'Utility Cargo / Olive',
    price: 3799,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A muted olive cargo for the urban wanderer. Heavyweight stonewashed canvas, breathable in Indian heat.',
    fabric: '340 GSM Stonewashed Canvas',
    colorway: 'Olive Green',
    gradient: 'linear-gradient(160deg, #7A7F6A 0%, #5E6250 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(80, 88, 68, 0.22)',
    fabricStory: {
      label: 'STONEWASHED CANVAS',
      body: 'Developed for structured drape and everyday movement, this heavyweight canvas construction undergoes a stonewashing process that softens the hand-feel while preserving the integrity of the weave. The result is a garment that feels broken-in from day one.',
      spec: { gsm: '340 GSM', weave: 'Canvas Twill', washMethod: 'Stonewash', finish: 'Stone Softened', softness: 'Medium' },
      lines: ['Heavyweight structure.', 'Stone-softened surface.', 'Built for the urban wanderer.'],
    },
    badges: ['Stonewashed Canvas', 'Heavyweight Twill', 'Relaxed Utility Fit'],
    dna: {
      fabric:    '340 GSM Stonewashed Canvas',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Stonewashed',
      movement:  'Designed for Everyday Wear',
      climate:   'Warm Climate Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Reinforced seam at cargo pocket openings',
      'Relaxed stacked hem with clean finish',
      'Structured waistband with internal facing',
      'Double-needle topstitch at all seams',
    ],
    fitPhilosophy: 'Designed with a wider leg opening and structured canvas drape to create natural stacking at the hem. The silhouette moves with the body while maintaining architectural form.',
    colorStory: { shade: 'Olive', description: 'A muted military-inspired olive, softened through stonewashing to reveal warmer, earthier undertones. Neither army green nor khaki — a precise in-between.' },
    stylingWith: ['Oversized heavyweight tee', 'Relaxed canvas overshirt', 'Low-profile utility footwear'],
    care: 'Machine wash cold, inside out. Line dry preferred. The stonewashed surface will develop subtle fading character at wear points over time.',
    designedFor: ['Everyday movement', 'Warm climate utility', 'Structured urban wear'],
    whyItExists: 'Built to bridge structured utility with contemporary everyday wear — heavyweight enough to hold form, softened enough to live in.',
    images: [
      { src: '/cargos/cargo-olive-green-front.png',   view: 'front'   },
      { src: '/cargos/cargo-olive-green-back.png',    view: 'back'    },
      { src: '/cargos/cargo-olive-green-side.png',    view: 'side'    },
      { src: '/cargos/cargo-olive-green-details.png', view: 'details' },
    ],
  },
  {
    id: 'cargo-01',
    name: 'Utility Cargo / Charcoal',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'Six-pocket utilitarian cargo cut in 320 GSM bio-washed cotton twill. Structured drape, relaxed fit.',
    fabric: '320 GSM Bio-Washed Cotton Twill',
    colorway: 'Charcoal Grey',
    gradient: 'linear-gradient(160deg, #4A4844 0%, #36332E 100%)',
    status: 'NIVENXA ESSENTIAL',
    atmosphereColor: 'rgba(54, 51, 46, 0.22)',
    fabricStory: {
      label: 'BIO-WASHED COTTON TWILL',
      body: 'A dense cotton twill construction treated through bio-washing to achieve a softened hand-feel without compromising structural integrity. The diagonal weave pattern provides natural stretch resistance and long-term durability.',
      spec: { gsm: '320 GSM', weave: 'Diagonal Twill', washMethod: 'Bio-Wash', finish: 'Bio-Washed', softness: 'Medium-Firm' },
      lines: ['Dense twill structure.', 'Bio-washed for softness.', 'Built for movement and everyday durability.'],
    },
    badges: ['Heavyweight Twill', 'Structured Drape', 'Bio-Washed'],
    dna: {
      fabric:    '320 GSM Bio-Washed Cotton Twill',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Bio-Washed Softening',
      movement:  'Designed for Everyday Wear',
      climate:   'All-Season Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Bio-washed cotton twill body',
      'Structured drape at thigh and knee',
      'Clean-finished cargo pocket openings',
      'Reinforced bar-tack at all pocket corners',
    ],
    fitPhilosophy: 'A structured utility silhouette designed for natural movement. The diagonal twill weave creates inherent body that holds the silhouette without restriction.',
    colorStory: { shade: 'Charcoal', description: 'Bio-washed charcoal — a dark neutral with graphite undertones. Warmer than black, more grounded than grey. A versatile foundation for any wardrobe.' },
    stylingWith: ['White oversized tee', 'Technical overshirt', 'Clean minimal footwear'],
    care: 'Machine wash cold, inside out. Tumble dry low. The bio-wash finish maintains colour integrity wash after wash.',
    designedFor: ['All-season utility', 'Daily movement', 'Minimal wardrobe systems'],
    whyItExists: 'Built as a foundational utility piece — structured enough to hold form across seasons, neutral enough to anchor any wardrobe.',
    images: [
      { src: '/cargos/cargo-charcoal-grey-front.png',   view: 'front'   },
      { src: '/cargos/cargo-charcoal-grey-back.png',    view: 'back'    },
      { src: '/cargos/cargo-charcoal-grey-side.png',    view: 'side'    },
      { src: '/cargos/cargo-charcoal-grey-details.png', view: 'details' },
    ],
  },

  // ─── Unisex Cargo Pants — Navy Blue ──────────────────────────────────────────
  {
    id: 'cargo-04',
    name: 'Utility Cargo / Navy Blue',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A deep navy cargo in 320 GSM bio-washed cotton twill. Structured silhouette, refined utility.',
    fabric: '320 GSM Bio-Washed Cotton Twill',
    colorway: 'Navy Blue',
    gradient: 'linear-gradient(160deg, #2E3A52 0%, #1C2840 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(30, 40, 64, 0.22)',
    fabricStory: {
      label: 'BIO-WASHED COTTON TWILL',
      body: 'The same dense cotton twill construction as the Charcoal, treated through bio-washing and finished in a deep navy that reads almost indigo in low light. Holds its structure across seasons.',
      spec: { gsm: '320 GSM', weave: 'Diagonal Twill', washMethod: 'Bio-Wash', finish: 'Bio-Washed', softness: 'Medium-Firm' },
      lines: ['Deep navy diagonal twill.', 'Bio-washed for softness.', 'Structured enough for form, relaxed enough for life.'],
    },
    badges: ['Heavyweight Twill', 'Structured Drape', 'Bio-Washed'],
    dna: {
      fabric:    '320 GSM Bio-Washed Cotton Twill',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Bio-Washed Softening',
      movement:  'Designed for Everyday Wear',
      climate:   'All-Season Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Bio-washed cotton twill body',
      'Structured drape at thigh and knee',
      'Clean-finished cargo pocket openings',
      'Reinforced bar-tack at all pocket corners',
    ],
    designedFor: ['All-season utility', 'Daily movement', 'Minimal wardrobe systems'],
    images: [
      { src: '/cargos/cargo-navy blue-front.png',  view: 'front'   },
      { src: '/cargos/cargo-navy blue-back.png',   view: 'back'    },
      { src: '/cargos/cargo-navy blue-side.png',   view: 'side'    },
      { src: '/cargos/cargo-navy blue-detail.png', view: 'details' },
    ],
  },

  // ─── Unisex Cargo Pants — Dark Olive ─────────────────────────────────────────
  {
    id: 'cargo-05',
    name: 'Utility Cargo / Dark Olive',
    price: 3799,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'A deep forest olive cargo in 340 GSM stonewashed canvas. Heavier hand, richer tone — built for longevity.',
    fabric: '340 GSM Stonewashed Canvas',
    colorway: 'Dark Olive',
    gradient: 'linear-gradient(160deg, #4A5240 0%, #343B2C 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(52, 59, 44, 0.22)',
    fabricStory: {
      label: 'STONEWASHED CANVAS',
      body: 'A darker, denser take on the Olive Green — the same stonewashed canvas construction pushed into a deeper forest tone. Heavier hand, richer colour depth, built for longevity.',
      spec: { gsm: '340 GSM', weave: 'Canvas Twill', washMethod: 'Stonewash', finish: 'Stone Softened', softness: 'Medium' },
      lines: ['Deep forest olive.', 'Stonewashed canvas structure.', 'Built to age with character.'],
    },
    badges: ['Stonewashed Canvas', 'Heavyweight Twill', 'Relaxed Utility Fit'],
    dna: {
      fabric:    '340 GSM Stonewashed Canvas',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Stonewashed',
      movement:  'Designed for Everyday Wear',
      climate:   'Warm Climate Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Reinforced seam at cargo pocket openings',
      'Relaxed stacked hem with clean finish',
      'Structured waistband with internal facing',
      'Double-needle topstitch at all seams',
    ],
    designedFor: ['Everyday movement', 'Warm climate utility', 'Structured urban wear'],
    images: [
      { src: '/cargos/cargo-dark-olive-front.png',   view: 'front'   },
      { src: '/cargos/cargo-dark-olive-back.png',    view: 'back'    },
      { src: '/cargos/cargo-dark-olive-side.png',    view: 'side'    },
      { src: '/cargos/cargo-dark-olive-details.png', view: 'details' },
    ],
  },

  // ─── Unisex Cargo Pants — Jet Black ──────────────────────────────────────────
  {
    id: 'cargo-06',
    name: 'Utility Cargo / Jet Black',
    price: 3499,
    category: 'cargo-pants',
    gender: 'unisex',
    description: 'Six-pocket utility cargo in 320 GSM bio-washed cotton twill. Pure jet black — clean, uncompromising, foundational.',
    fabric: '320 GSM Bio-Washed Cotton Twill',
    colorway: 'Jet Black',
    gradient: 'linear-gradient(160deg, #1E1E1E 0%, #0F0F0F 100%)',
    status: 'NIVENXA ESSENTIAL',
    atmosphereColor: 'rgba(15, 15, 15, 0.25)',
    fabricStory: {
      label: 'BIO-WASHED COTTON TWILL',
      body: 'The same dense diagonal twill construction as the Charcoal, finished in a pure jet black that holds its depth wash after wash. Bio-washing softens the hand without dulling the colour.',
      spec: { gsm: '320 GSM', weave: 'Diagonal Twill', washMethod: 'Bio-Wash', finish: 'Bio-Washed', softness: 'Medium-Firm' },
      lines: ['Pure jet black twill.', 'Bio-washed for softness.', 'Colour integrity, wash after wash.'],
    },
    badges: ['Heavyweight Twill', 'Structured Drape', 'Bio-Washed'],
    dna: {
      fabric:    '320 GSM Bio-Washed Cotton Twill',
      structure: 'Relaxed Utility Silhouette',
      finish:    'Bio-Washed Softening',
      movement:  'Designed for Everyday Wear',
      climate:   'All-Season Utility',
    },
    details: [
      'Six-pocket utility construction',
      'Bio-washed cotton twill body',
      'Structured drape at thigh and knee',
      'Clean-finished cargo pocket openings',
      'Reinforced bar-tack at all pocket corners',
    ],
    designedFor: ['All-season utility', 'Daily movement', 'Minimal wardrobe systems'],
    images: [
      { src: '/cargos/cargo-jet-black-front.png',  view: 'front'   },
      { src: '/cargos/cargo-jet-black-back.png',   view: 'back'    },
      { src: '/cargos/cargo-jet-black-side.png',   view: 'side'    },
      { src: '/cargos/cargo-jet-black-detail.png', view: 'details' },
    ],
  },

  // ─── Unisex Oversize Tee Shirts ───────────────────────────────────────────────
  {
    id: 'tee-01',
    name: 'Heritage Tee / Ecru',
    price: 1999,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Boxy drop-shoulder silhouette in dense 240 GSM combed cotton jersey. The foundational piece.',
    fabric: '240 GSM Combed Cotton Jersey',
    colorway: 'Ecru White',
    gradient: 'linear-gradient(160deg, #EAE5D8 0%, #D4CFBF 100%)',
    status: 'CORE ESSENTIAL',
    atmosphereColor: 'rgba(234, 229, 216, 0.25)',
    fabricStory: {
      label: 'COMBED COTTON JERSEY',
      lines: ['240 GSM dense weight.', 'Drop-shoulder construction.', 'The foundational NIVENXA piece.'],
    },
    badges: ['Combed Cotton', 'Drop Shoulder', 'Core Silhouette'],
    dna: { fit: 'Boxy Oversized', fabric: 'Combed Cotton Jersey', finish: 'Natural', drape: 'Structured', movement: 'Everyday Uniform' },
  },
  {
    id: 'tee-02',
    name: 'Terracotta Washed Tee',
    price: 1999,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Sun-baked terracotta pigment dye over a structured oversized form. Earthy, lived-in warmth.',
    fabric: '240 GSM Pigment-Dyed Cotton',
    colorway: 'Sun-Baked Terracotta',
    gradient: 'linear-gradient(160deg, #C47055 0%, #A05040 100%)',
    status: 'NEW SEASON',
    atmosphereColor: 'rgba(196, 112, 85, 0.2)',
    fabricStory: {
      label: 'PIGMENT-DYED COTTON',
      lines: ['Sun-baked mineral tone.', 'Pigment-dyed for lived-in warmth.', 'Fades beautifully with wear.'],
    },
    badges: ['Pigment Dyed', 'Lived-In Wash', 'Oversized Form'],
    dna: { fit: 'Boxy Oversized', fabric: 'Pigment-Dyed Cotton', finish: 'Pigment Washed', drape: 'Structured', movement: 'Everyday Uniform' },
  },
  {
    id: 'tee-03',
    name: 'Ink Drop Graphic Tee',
    price: 2199,
    category: 'over-tee-shirts',
    gender: 'unisex',
    description: 'Minimal hand-drawn graphic on heavyweight charcoal jersey. Ring-spun for softness that ages beautifully.',
    fabric: '260 GSM Ring-Spun Cotton',
    colorway: 'Washed Charcoal',
    gradient: 'linear-gradient(160deg, #4A4844 0%, #36332E 100%)',
    status: 'LIMITED RUN',
    atmosphereColor: 'rgba(74, 72, 68, 0.2)',
    fabricStory: {
      label: 'RING-SPUN COTTON',
      lines: ['260 GSM ring-spun weight.', 'Hand-drawn graphic detail.', 'Softens and ages beautifully.'],
    },
    badges: ['Ring-Spun Cotton', 'Hand-Drawn Graphic', 'Limited Run'],
    dna: { fit: 'Boxy Oversized', fabric: 'Ring-Spun Cotton', finish: 'Natural', drape: 'Structured', movement: 'Editorial Everyday' },
  },
]

export const getProductsByCategory = (category: Product['category']) =>
  products.filter((p) => p.category === category)

export const getProductsByGender = (gender: Product['gender']) =>
  products.filter((p) => p.gender === gender)
